title: Ananthakrishnan Kaimal
description: My personal portfolio and achievements 
theme: minima
author:
  name: Ananthakrishnan Kaimal
  email: specatak30@gmail.com
social_link:
  github: Greygoose-computation 
